seed: 1234
mode: train  # or "eval" for evaluation
output_dir: ./output/PhyLSTM2  # 模型保存的根目录
use_tbd: False
use_vdl: False

# Model configuration
MODEL:
  input_size: 1  # matches ag_data.shape[2]
  hidden_size: 100  # matches LSTM layer size in original code
  model_type: 2  # or whatever type you've defined
  dtype: "float64"  # 确保使用float64

# Training configuration
TRAIN:
  epochs: 100  # 增加训练轮次以获得更好的模型
  iters_per_epoch: 2000
  save_freq: 50  # 每50轮保存一次检查点
  learning_rate: 1e-3
  checkpoint_path: null  # 恢复训练时的检查点路径
  model_save_dir: "saved_models"  # 模型保存的子目录

# Evaluation configuration
EVAL:
  pretrained_model_path: null  # 评估时加载模型的路径
  eval_with_no_grad: true

# Data configuration
#DATA_FILE_PATH: "./data/data_SanBernardino.mat"
DATA_FILE_PATH: "./data/data_boucwen.mat"
batch_size: 1
num_workers: 0

# Logging configuration
log_freq: 50